// import type { Metadata } from "next";
// import "./globals.css";  // Asegúrate de tener tu CSS básico aquí

// export const metadata: Metadata = {
//   title: "〄M&C | Innovative IT Consulting for Business Growth and Development | Your Partner in Work",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body style={{ fontFamily: 'Arial, Helvetica, sans-serif' }}>
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: " 〄M&C | Innovative IT Consulting for Business Growth and Development | Your Partner in Work",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
